config/routes.rb
FileUpload::Application.routes.draw do
  resources :upload do
    collection do
     post 'uploadfile'
    end
  end

root :to => "upload#index"

end

app/models/data_file.rb
class DataFile < ActiveRecord::Base
 def self.save(upload, upload1)

    name =  upload['datafile'].original_filename
    name1 =  upload1['datafile1'].original_filename
    directory = "public/data"
    # create the file path
    path = File.join(directory, name)
    path1 = File.join(directory, name1)
    # write the file
    File.open(path, "wb") { |f| f.write(upload['datafile'].read) }
    File.open(path1, "wb") { |f| f.write(upload1['datafile1'].read) }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/upload_controller.rb
class UploadController < ApplicationController
 def index

end


  def uploadfile
    post = DataFile.save(params[:upload],params[:upload1])
    render :text => "File has been uploaded successfully"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/upload_helper.rb
module UploadHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FileUpload</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/upload/index.html.erb
<h1>File Upload</h1>
<% form_tag(uploadfile_upload_index_path,:method => 'post', :multipart => true) do %>
<p><label for="upload_file">Select File</label> :
<%= file_field 'upload', 'datafile' %></p>
<%= file_field 'upload1', 'datafile1' %></p>
<%= submit_tag "Upload" %>
<% end %>